### ISSUE TITLE
Handle errors for fetch requests

### ISSUE THREAD

**Issue by andrushkin2** [ilya-kovshik/form-translate#11]
Need to handle error in the next requests:

https://github.com/ilya-kovshik/form-translate/blob/5d39d6442b6aa210fd7202a946598254df0d4a7c/src/pages/ticket/index.tsx#L322

https://github.com/ilya-kovshik/form-translate/blob/5d39d6442b6aa210fd7202a946598254df0d4a7c/src/pages/ticket/index.tsx#L336

**Comment by ilya-kovshik** [comment]
Updates have been pushed - [commit](https://github.com/ilya-kovshik/form-translate/commit/bc3638617c99e5f95b07b67e241c90254bf10146)

**Comment by ilya-kovshik** [comment]
Updates have been pushed - [commit](https://github.com/ilya-kovshik/form-translate/commit/2b351e7760504f24e6fd6f387f5402c853a6944a)
