### ISSUE TITLE
Wrong BEM naming

### ISSUE THREAD

**Issue by andrushkin2** [ilya-kovshik/form-translate#12]
https://github.com/ilya-kovshik/form-translate/blob/a5976bc168976b9f6c53d21b1ba2e7eb901fc1da/src/components/header/index.tsx#L44

`primary-button_size-normal` - wrong BEM naming

If `size-normal` is a modifier, then the class should be `primary-button--size-normal`

**Comment by ilya-kovshik** [comment]
Updates have been pushed - [commit](https://github.com/ilya-kovshik/form-translate/commit/719ba866b04a2d4f2ab5ad97078986072b580b54)

**Comment by andrushkin2** [comment]
@ikovshik look at my comment inside the commit

**Comment by ilya-kovshik** [comment]
@andrushkin2 
Updates have been pushed - [commit](https://github.com/ilya-kovshik/form-translate/commit/4e123824dd8c90f63f476e02a28f9870fedba896)

**Comment by andrushkin2** [comment]
@ikovshik 
See comment in the [commit](https://github.com/ilya-kovshik/form-translate/commit/4e123824dd8c90f63f476e02a28f9870fedba896)

**Comment by ilya-kovshik** [comment]
@andrushkin2 
Fixes have been pushed - [commit](https://github.com/ilya-kovshik/form-translate/commit/4b364a30fcd4a5e8eda6c2dc616a0a0075b9e8f3)
