### ISSUE TITLE
Missed 'useCallback' dependency

### ISSUE THREAD

**Issue by andrushkin2** [ilya-kovshik/form-translate#13]
Missed 'useCallback' dependency:

<img width="700" alt="Missed 'useCallback' dependency" src="https://user-images.githubusercontent.com/3307543/165291283-824befff-e04b-41df-bee7-d02758018bf9.png">

**Comment by ilya-kovshik** [comment]
Fix with warning has been pushed - [commit](https://github.com/ilya-kovshik/form-translate/commit/e4de661bf0537501d10428e088e67fe26bc3be92)
