### ISSUE TITLE
There is no "npm run ci" command

### ISSUE THREAD

**Issue by andrushkin2** [ilya-kovshik/form-translate#14]
There is no `npm run ci` command that's listed in the project README:

<img width="700" alt="Screenshot 2022-04-26 at 14 36 34" src="https://user-images.githubusercontent.com/3307543/165291614-bc85b357-9346-4d53-b571-8cfc59ac3737.png">

**Comment by ilya-kovshik** [comment]
Fix with description has been pushed - [commit](https://github.com/ilya-kovshik/form-translate/commit/88b3c3909b890c93ebcf45586dec33c956621616)
