### ISSUE TITLE
I can create a 'MYG' case with spaces only instead of numbers

### ISSUE THREAD

**Issue by andrushkin2** [ilya-kovshik/form-translate#17]
Add spaces only and try to submit. We need to handle this and check case number:

<img width="1083" alt="Screenshot 2022-05-05 at 12 13 09" src="https://user-images.githubusercontent.com/3307543/166895573-cf3fafd9-fe8b-482d-8097-f66f333f8b9f.png">

**Comment by ilya-kovshik** [comment]
Fix has been pushed - [commit](https://github.com/ilya-kovshik/form-translate/commit/ecce8d14ce485666384f451a0a727ea5325ec388)

**Comment by andrushkin2** [comment]
@ikovshik see my comment in the [commit](https://github.com/ilya-kovshik/form-translate/commit/ecce8d14ce485666384f451a0a727ea5325ec388)

**Comment by ilya-kovshik** [comment]
Fix has been pushed - [commit](https://github.com/ilya-kovshik/form-translate/commit/57d795ccfd92ed5df31c7bd4c95a9f395630be7b)
