### ISSUE TITLE
Prevent creation of same MYG cases

### ISSUE THREAD

**Issue by andrushkin2** [ilya-kovshik/form-translate#19]
We should prevent creation of same MYG cases like on the pic below.
Need to check existing MYG cases when creating a new one

<img width="554" alt="Screenshot 2022-05-05 at 12 53 51" src="https://user-images.githubusercontent.com/3307543/166900983-8b0384d3-ceba-4784-b4e1-0aa997eeafa2.png">

**Comment by ilya-kovshik** [comment]
@andrushkin2 
Here I was thinking that we could have cases when we need to have few groups of translations for the same ticket (for example, one group where we definitely want to send and the different one just a draft).

Ok, I can implement it in the following way - when user enters the name of the ticket (on the ticket page) and this name is already exists I can show warning and if user still leave the page - translation won't be saved.

**Comment by ilya-kovshik** [comment]
I've clarified the requirements to the following case with Dima and he said that such behavior is fine for now.
