### ISSUE TITLE
Useless link

### ISSUE THREAD

**Issue by andrushkin2** [ilya-kovshik/form-translate#20]
I didn't quite get what for the link to open a case that's already opened:

<img width="1040" alt="Screenshot 2022-05-05 at 12 57 41" src="https://user-images.githubusercontent.com/3307543/166901437-309d0f19-6711-414f-83e4-1f14c680bf1e.png">

**Comment by ilya-kovshik** [comment]
Fix has been pushed - [commit](https://github.com/ilya-kovshik/form-translate/commit/36d60bfcb1dbefbebf24863d770791688e9bc92f)
