### ISSUE TITLE
Rename 'Submit' button

### ISSUE THREAD

**Issue by andrushkin2** [ilya-kovshik/form-translate#21]
It's hard for me to understand what the "Submit" does. I thought it saves all translations that I added for the MYG case, but it sends all the translations to the Google Spreadsheet.
We should rename the button to something like `Send translations` or `Submit translations`

<img width="656" alt="Screenshot 2022-05-05 at 12 59 09" src="https://user-images.githubusercontent.com/3307543/166902261-6f3ff9c6-e7ff-40a9-ba62-9e4f0b29ab4e.png">

**Comment by ilya-kovshik** [comment]
Fix has been pushed - [commit](https://github.com/ilya-kovshik/form-translate/commit/de86f842684a9a2ffda524a084f267b8db7b3f1e)
