### ISSUE TITLE
Cannot select "Other" release version

### ISSUE THREAD

**Issue by andrushkin2** [ilya-kovshik/form-translate#22]
1. Switch the release selector to "Other" option
2. An extra input will be shown, but the release selector will be switched back to an empty value:

<img width="1042" alt="Screenshot 2022-05-05 at 13 06 31" src="https://user-images.githubusercontent.com/3307543/166902895-ef9d75a5-6c08-4466-8bac-01109690c2f5.png">

**Comment by ilya-kovshik** [comment]
Fix has been pushed - [commit](https://github.com/ilya-kovshik/form-translate/commit/9be4917a57b5d597844cd24e7626503019a7e600)
