### ISSUE TITLE
Upgrade app to React v18

### ISSUE THREAD

**Issue by andrushkin2** [ilya-kovshik/form-translate#3]
https://github.com/ilya-kovshik/form-translate/blob/5d39d6442b6aa210fd7202a946598254df0d4a7c/src/index.tsx#L17

React 18 was realesed a few week ago. It has a few excellent performance feature we can use. 
Is it possible to upgrade the React to the latest version?

**Comment by ilya-kovshik** [comment]
Updates with React v18 have been pushed - [commit](https://github.com/ilya-kovshik/form-translate/commit/a5976bc168976b9f6c53d21b1ba2e7eb901fc1da)
