### ISSUE TITLE
Add 'exhaustive-deps' plugin to ESLint rules

### ISSUE THREAD

**Issue by andrushkin2** [ilya-kovshik/form-translate#4]
Look at the [article](https://maxrozen.com/react-hooks-eslint-plugin-saved-hours-debugging-useeffect)

There's a very helpful ESLint plugin for `useEffect` checking. I don't say you've missed something, but, you know, we all make mistakes.

**Comment by ilya-kovshik** [comment]
Updates have been pushed - [commit](https://github.com/ilya-kovshik/form-translate/commit/6c1b09bab88e1212ac06f8a1c92b4cb35031ff54).
