### ISSUE TITLE
Get rid of useless `as boolean` usage

### ISSUE THREAD

**Issue by andrushkin2** [ilya-kovshik/form-translate#5]
https://github.com/ilya-kovshik/form-translate/blob/5d39d6442b6aa210fd7202a946598254df0d4a7c/src/pages/ticket/index.tsx#L35

Do need to use 'as boolean'. TS will understands the boolean type if you set `false` to `useState` func.

**Comment by ilya-kovshik** [comment]
Without 'as boolean' I'm getting the following error:

```
Type '[false, Dispatch<SetStateAction<false>>]' is not assignable to type '[boolean, Dispatch<SetStateAction<boolean>>]'.
  Type at position 1 in source is not compatible with type at position 1 in target.
    Type 'Dispatch<SetStateAction<false>>' is not assignable to type 'Dispatch<SetStateAction<boolean>>'.
      Type 'SetStateAction<boolean>' is not assignable to type 'SetStateAction<false>'.
        Type 'true' is not assignable to type 'SetStateAction<false>'.
```

But without explicit type (`const [isStateValid, setIsValidState] = useState(false);`) it shows the same types/interfaces:

![image](https://user-images.githubusercontent.com/46033063/164501310-ec537559-8c93-43f4-8166-35d4ab1024e2.png)
![image](https://user-images.githubusercontent.com/46033063/164501492-bd6a84bf-0d2e-4df7-a7e8-394e16d43170.png)

**Comment by andrushkin2** [comment]
@ikovshik  

### 1) There're no errors if I declare it like this:

```js
const [isStateValid, setIsValidState] = useState<boolean>(false);
```

<img width="700" alt="Screenshot 2022-04-26 at 14 54 39" src="https://user-images.githubusercontent.com/3307543/165294549-49ea3aa9-7c02-479a-a2f1-8fc3f083430f.png">


### 2) Also there're no errors if I declare it like this:

```js
const [isStateValid, setIsValidState] = useState(false);
```

<img width="700" alt="Screenshot 2022-04-26 at 14 57 01" src="https://user-images.githubusercontent.com/3307543/165294817-80f5a518-b2f2-42ee-a195-9383a9e4b0bf.png">

**Comment by ilya-kovshik** [comment]
Update has been pushed - [commit](https://github.com/ilya-kovshik/form-translate/commit/9cad8bbf31ec8c3b010ea711ddfca7efa810efc8)

**Comment by andrushkin2** [comment]
@ikovshik could you look through all files and get rid of `as` assignments like this.

**Comment by ilya-kovshik** [comment]
@andrushkin2 
Updates have been pushed - [commit](https://github.com/ilya-kovshik/form-translate/commit/7797eebeb4f32dc3fff440ac201f62b9d21ce63a)

**Comment by andrushkin2** [comment]
Left a comment in the [commit](https://github.com/ilya-kovshik/form-translate/commit/7797eebeb4f32dc3fff440ac201f62b9d21ce63a)

**Comment by ilya-kovshik** [comment]
@andrushkin2 
Updates have been pushed - [commit](https://github.com/ilya-kovshik/form-translate/commit/02dbe030a1759281e2275771a21d9eb92d54ed1b)
