### ISSUE TITLE
Move 'isTranslationsEmpty' util  to a separated file with helpers

### ISSUE THREAD

**Issue by andrushkin2** [ilya-kovshik/form-translate#6]
https://github.com/ilya-kovshik/form-translate/blob/5d39d6442b6aa210fd7202a946598254df0d4a7c/src/pages/ticket/index.tsx#L46

**Comment by ilya-kovshik** [comment]
Update has been pushed - [commit](https://github.com/ilya-kovshik/form-translate/commit/887a16cd40d780490b303d778b9ecee3abcb77c1)
