### ISSUE TITLE
Move the block of code to a separated util

### ISSUE THREAD

**Issue by andrushkin2** [ilya-kovshik/form-translate#7]
https://github.com/ilya-kovshik/form-translate/blob/5d39d6442b6aa210fd7202a946598254df0d4a7c/src/pages/ticket/index.tsx#L67

We can move the code inside the `if` statement to a separated util that will return a `ticker` or `undefined` and then we can update the component state if need it.

**Comment by ilya-kovshik** [comment]
Updates have been pushed - [commit](https://github.com/ilya-kovshik/form-translate/commit/3b9b518e7c60f2896da20f4d6d69fc53ed86e694)

**Comment by andrushkin2** [comment]
@ikovshik left a comment inside the commit

**Comment by ilya-kovshik** [comment]
@andrushkin2 
Updates have been pushed - [commit](https://github.com/ilya-kovshik/form-translate/commit/47ad66fe1778149020df227da3952c8d5bffa89e)
