### ISSUE TITLE
Move 'saveToLocalStorage' function to a separated file

### ISSUE THREAD

**Issue by andrushkin2** [ilya-kovshik/form-translate#8]
https://github.com/ilya-kovshik/form-translate/blob/5d39d6442b6aa210fd7202a946598254df0d4a7c/src/pages/ticket/index.tsx#L86

**Comment by ilya-kovshik** [comment]
Update has been pushed - [commit](https://github.com/ilya-kovshik/form-translate/commit/acaad058f4db556b1be266be99adccedf3a30abe)

**Comment by ilya-kovshik** [comment]
@andrushkin2 
Updates have been pushed - [commit](https://github.com/ilya-kovshik/form-translate/commit/6ca87ec989acab316564aea232b8f67716003d42)

**Comment by andrushkin2** [comment]
Look at my comment inside the commit

**Comment by ilya-kovshik** [comment]
Fix with typo has been pushed - [commit](https://github.com/ilya-kovshik/form-translate/commit/daac3c23ba027d7a5c5e59ba4cb012f070c3b5e9)
