### ISSUE TITLE
Move 'removeFromLocalStorage' to a separated file

### ISSUE THREAD

**Issue by andrushkin2** [ilya-kovshik/form-translate#9]
https://github.com/ilya-kovshik/form-translate/blob/5d39d6442b6aa210fd7202a946598254df0d4a7c/src/pages/ticket/index.tsx#L101

**Comment by ilya-kovshik** [comment]
Update has been pushed - [commit](https://github.com/ilya-kovshik/form-translate/commit/4a04e512ba2f2fe59f17ae01e68304e48b04e1db)

**Comment by ilya-kovshik** [comment]
@andrushkin2 
Updates have been pushed - [commit](https://github.com/ilya-kovshik/form-translate/commit/6ca87ec989acab316564aea232b8f67716003d42)
